name: firmflow
description: Production standard firm management application.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6           # State Management
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  intl: ^0.19.0         # Formatting
  pdf: ^3.10.4          # PDF Generation
  printing: ^5.11.0     # PDF Printing

flutter:
  uses-material-design: true